# Generated by Django 5.1.4 on 2024-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_project_skill_youtubevideo_aboutme_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter your project slug', unique=True),
        ),
    ]
