# Generated by Django 5.1.4 on 2025-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0004_alter_aboutme_user_alter_youtubevideo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='social_media',
            field=models.CharField(blank=True, help_text='Add your social media links', null=True),
        ),
    ]
