# Generated by Django 5.1.4 on 2025-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0005_alter_aboutme_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='social_media',
            field=models.JSONField(blank=True, help_text='Add your social media links', null=True),
        ),
    ]
