# Generated by Django 5.1.4 on 2025-01-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0007_rename_about_me_aboutme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='my_website.project'),
        ),
    ]
